using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;
using Autodesk.AutoCAD.Runtime;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyConfiguration("Production")]
[assembly: CommandClass(null)]
[assembly: SecurityRules(SecurityRuleSet.Level1)]
[assembly: CLSCompliant(true)]
[assembly: ComVisible(false)]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCopyright("©Autodesk, Inc. 1998-2022. All rights reserved.")]
[assembly: AssemblyProduct("AeccMgdReverse")]
[assembly: AssemblyCompany("Autodesk, Inc.")]
[assembly: ExtensionApplication(null)]
[assembly: AssemblyDescription("")]
[assembly: AssemblyTitle("AeccMgdReverse")]
[assembly: ReferenceAssembly]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
